apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
resources:
  - ../base/portfolio-rebalancer
  - ingress.yaml
