apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portfolio-rebalancer
  namespace: portfolio-rebalancer
spec:
  chart:
    spec:
      version: ">=0.0.0"
  values:
    ingress:
      hosts:
        - host: portfolio-rebalancer.localhost
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: pr
                    port:
                      number: 80