apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portfolio-rebalancer
  namespace: portfolio-rebalancer
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    ingress:
      hosts:
        - host: portfolio-rebalancer.localhost
          paths:
            - path: /
              pathType: ImplementationSpecific