apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfc-deployment
  labels:
    app: dfc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dfc
  template:
    metadata:
      labels:
        app: dfc
    spec:
      containers:
        - name: nginx
          image: public.ecr.aws/f8t1b2c5/amast/debt-free-calculator:0.1.0
          ports:
            - containerPort: 80
              name: dfc-port
---
apiVersion: v1
kind: Service
metadata:
  name: dfc-service
spec:
  selector:
    app: dfc
  type: ExternalName
  externalName: debt-free-calculator.aaronmast.dev
  ports:
    - name: dfc-service-port
      protocol: TCP
      port: 80
      targetPort: dfc-port