---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: portfolio-rebalancer
  namespace: portfolio-rebalancer
spec:
  interval: 30s
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: portfolio-rebalancer
  targetNamespace: portfolio-rebalancer